### ISSUE TITLE
Enchancement: Hinting system

### ISSUE THREAD

**Issue by dz0** [daveagp/websheets#4]
After failed try, student could get some hint(s).
They could be listed at the end of each \\[]\ area (or end of line in multiline areas).

This could make process more interesting.

**Comment by daveagp** [comment]
I would think that there are 2 good ways to do this:
 1. put them in the description with extra markup (CS Circles does this kind of thing using popups). this is much easier, but exposes hints from the beginning.
 2. add them as extra websheet fields and only make hints visible once a certain number of solutions have been attempted. this would be a lot more work but much more pedagogically interesting. 

I don't have time to implement this myself but I would support if you are interested to try it out.

**Comment by dz0** [comment]
hints could come alongside each test and be shown if test doesn't pass.

This could serve as comments/explanations for tests,themselves --  so it would be easier to maintain test collections..
