### ISSUE TITLE
notify_new  is not triggered for "copied" sheets

### ISSUE THREAD

**Issue by dz0** [daveagp/websheets#5]
I noticed this as my server doesn't have smtp configured and throws error on trying to mail.

So the error is thrown on creation of new (blank) sheet, but not on copying sheet to new one.

**Comment by daveagp** [comment]
Thanks for noticing both of these issues. I'll do my best to fix them tomorrow since I just got back from a trip.

**Comment by dz0** [comment]
No rush :-)

**Comment by daveagp** [comment]
Should be resolved by https://github.com/daveagp/websheets/commit/6fb09d3ef47b3f09ad7d86f6531c6a7d2d9d4c14
