### ISSUE TITLE
How can teachers see students solutions?

### ISSUE THREAD

**Issue by dz0** [daveagp/websheets#7]
Would be nice to see last (or all) versions of student submissions (similary as in CSCircles Py course).

**Comment by daveagp** [comment]
I agree :) I haven't had time to implement it. What would be involved is (1) fetching student solutions from the DB, which are json lists of code fragments, (2) loading the problem statements, (3) calling the methods on those problem statements to get a combined output, and (4) displaying it.

**Comment by dz0** [comment]
Maybe simple workaround would be to load students solution on teachers
login?

And/or maybe would be easy to  submit as anonymous (so teachers history
wouldn't mess up)?

**Comment by daveagp** [comment]
That would definitely be the easiest UI solution. You could copy the student's solution into the teacher's history, making it the most recent submission.

**Comment by daveagp** [comment]
Closed by https://github.com/daveagp/websheets/pull/10 :)
